[
  {
    "Name": "Alcohol Change of Ownership Form",
    "Record Type": "Alcohol/Amendment/Change of Ownership/NA",
    "Description": "This amendment form is used to provide necessary information when a licensed cannabis business changes ownership that does NOT result in change of controlling interest and/or business structure changes.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Alcohol License Amendment",
    "Record Type": "Alcohol/Amendment/License Modification/NA",
    "Description": "This amendment form will allow modifications of contact information be made to the license.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Alcohol Modification of Premises",
    "Record Type": "Alcohol/Amendment/Modification of Premises/NA",
    "Description": "This amendment form is used to provide necessary information when a licensed cannabis business would like to make modifications to the premises.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Alcoholic Beverage Control Case",
    "Record Type": "Alcohol/Enforcement/Case/NA",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Alcoholic Beverage Control Complaint",
    "Record Type": "Alcohol/Enforcement/Compliant/NA",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Alcohol Beverage Control Violation",
    "Record Type": "Alcohol/Enforcement/Violation/NA",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Individual Liquor Registration",
    "Record Type": "Alcohol/Entity/Individual/Registration",
    "Description": "Persons new to the corporation or limited liability company who have not previously been qualified must register:\nOfficers and Directors\nMembers and shareholders who own 10% or more of the business entity",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Alcoholic Beverage Manager License",
    "Record Type": "Alcohol/Entity/Manager/License",
    "Description": "A permit for an individual in actual control of the alcohol, wine, or beer operations of a licensed facility",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Alcoholic Beverage Manager Application",
    "Record Type": "Alcohol/Entity/Manager/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Alcoholic Beverage Manager Renewal",
    "Record Type": "Alcohol/Entity/Manager/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Alcoholic Beverage Server Permit",
    "Record Type": "Alcohol/Entity/Server/Permit",
    "Description": "A Server Permit allows any person to serve liquor, wine and high gravity beer at an establishment that holds an On-Premise Consumption License.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Alcoholic Beverage Caterer License",
    "Record Type": "Alcohol/LBD/Caterer/License",
    "Description": "Caterer: Sells and serves alcoholic beverages at catered events as part of the licensees preparation and service of food.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Alcoholic Beverage Caterer Application",
    "Record Type": "Alcohol/LBD/Caterer/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Alcoholic Beverage Caterer Renewal",
    "Record Type": "Alcohol/LBD/Caterer/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Amusement-Show-Exhibit Liquor License",
    "Record Type": "Alcohol/LBD/Entertainment Facility/License",
    "Description": "Sale of beer, wine, and liquor for consumption on the premises. \nAn Entertainment Facility - the primary business of which is to provide the public with sports or entertainment activities.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Amusement-Show-Exhibit Liquor Application",
    "Record Type": "Alcohol/LBD/Entertainment Facility/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Amusement-Show-Exhibit Liquor Renewal",
    "Record Type": "Alcohol/LBD/Entertainment Facility/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Airline Boat Train Liquor License",
    "Record Type": "Alcohol/LBD/Carrier/License",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Airline Boat Train Liquor Application",
    "Record Type": "Alcohol/LBD/Carrier/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Airline Boat Train Liquor Renewal",
    "Record Type": "Alcohol/LBD/Carrier/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "On-Premise Liquor License",
    "Record Type": "Alcohol/LBD/On Premise/License",
    "Description": "On-premise retailer: An establishment where alcoholic beverages may be purchased and consumed on the licensed premises. On-premises retailers include restaurants, taverns, nightclubs, hotels, bed and breakfasts, theaters, museums, sports facilities, passenger-carrying ships and trains.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "On-Premise Liquor Application",
    "Record Type": "Alcohol/LBD/On Premise/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "On-Premise Liquor Renewal",
    "Record Type": "Alcohol/LBD/On Premise/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Off-Premise Liquor License",
    "Record Type": "Alcohol/Retail/Off Premise/License",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Off-Premise Liquor Application",
    "Record Type": "Alcohol/Retail/Off Premise/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Off-Premise Liquor Renewal",
    "Record Type": "Alcohol/Retail/Off Premise/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Private Club Liquor License",
    "Record Type": "Alcohol/LBD/Private Club/License",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Private Club Liquor Application",
    "Record Type": "Alcohol/LBD/Private Club/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Private Club Liquor Renewal",
    "Record Type": "Alcohol/LBD/Private Club/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Restaurant Liquor License",
    "Record Type": "Alcohol/LBD/Restaurant/License",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Restaurant Liquor Application",
    "Record Type": "Alcohol/LBD/Restaurant/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Restaurant Liquor Renewal",
    "Record Type": "Alcohol/LBD/Restaurant/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Bed and Breakfast/Inn Liquor License",
    "Record Type": "Alcohol/Lodging/Bed and Breakfast Inn/License",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Bed and Breakfast/Inn Liquor Application",
    "Record Type": "Alcohol/Lodging/Bed and Breakfast Inn/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Bed and Breakfast/Inn Liquor Renewal",
    "Record Type": "Alcohol/Lodging/Bed and Breakfast Inn/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Hotel/Motel Liquor License",
    "Record Type": "Alcohol/Lodging/Hotel Motel/License",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Hotel/Motel Liquor Application",
    "Record Type": "Alcohol/Lodging/Hotel Motel/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Hotel/Motel Liquor Renewal",
    "Record Type": "Alcohol/Lodging/Hotel Motel/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Brew Pub Liquor Permit",
    "Record Type": "Alcohol/Retail/Brew Pub/Permit",
    "Description": "A brew pub is a retail establishment that manufactures no more than 1,860,000 gallons of beer on its premises each year. ABRA: Brew Pub Permit: Allows a restaurant, tavern, multipurpose facility, hotel or nightclub to brew beer on or adjacent to its licensed premises and to sell the beer for consumption at the establishment. Also allows the licensee to sell the beer it manufactures in cans, kegs, bottles, growlers and other sealed containers to wholesalers and patrons for off-premises consumption.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Retail Liquor Delivery Service License",
    "Record Type": "Alcohol/Retail/Delivery Service/License",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Retail Liquor Delivery Service Application",
    "Record Type": "Alcohol/Retail/Delivery Service/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Retail Liquor Delivery Service Renewal",
    "Record Type": "Alcohol/Retail/Delivery Service/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Distillery Pub Permit",
    "Record Type": "Alcohol/Retail/Distillery Pub/Permit",
    "Description": "ABRA: Distillery Pub Permit: Allows an on-premises establishment to manufacture, distill and store craft liquors on the licensed premises or in an area immediately adjacent to the premises. Also allows the licensee to sell the spirits in sealed bottles or other closed containers to wholesalers and patrons for off-premises consumption.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Fermented Malt Beverage License",
    "Record Type": "Alcohol/Retail/Fermented Malt Beverage/License",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Fermented Malt Beverage Application",
    "Record Type": "Alcohol/Retail/Fermented Malt Beverage/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Fermented Malt Beverage Renewal",
    "Record Type": "Alcohol/Retail/Fermented Malt Beverage/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Retail Liquor Store License",
    "Record Type": "Alcohol/Retail/Liquor Store/License",
    "Description": "Sale of beer, wine, and liquor by the package for off-premises consumption.  Retail Liquor Stores may sell non-food items related to the consumption of liquor (e.g. soft drinks and mixers; tobacco products; coasters, glasses, stir sticks, etc.)",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Retail Liquor Store Application",
    "Record Type": "Alcohol/Retail/Liquor Store/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Retail Liquor Store Renewal",
    "Record Type": "Alcohol/Retail/Liquor Store/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Optional Premises Liquor License",
    "Record Type": "Alcohol/Retail/Optional Premises/License",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Optional Premises Liquor Application",
    "Record Type": "Alcohol/Retail/Optional Premises/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Optional Premises Liquor Renewal",
    "Record Type": "Alcohol/Retail/Optional Premises/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Retail Package Store Liquor License",
    "Record Type": "Alcohol/Retail/Package Store/License",
    "Description": "Sale of beer, wine, and liquor by the package for off-premises consumption.  Must be licensed by the State Board of Pharmacy.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Retail Package Store Liquor Application",
    "Record Type": "Alcohol/Retail/Package Store/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Retail Package Store Liquor Renewal",
    "Record Type": "Alcohol/Retail/Package Store/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Tasting Liquor Permit",
    "Record Type": "Alcohol/Retail/Tasting/Permit",
    "Description": "An alcohol beverage Tastings Permit allows a retail liquor store or liquor-licensed drug store to conduct sample tastings of alcohol beverages within their own establishment.\nTasting Permit: Allows a manufacturer, retailer, wholesaler or private collector to provide customers with a tasting of products on a portion of the licensed premises or licensed storage facility.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Art Gallery Liquor Permit",
    "Record Type": "Alcohol/Specialty/Art Gallery/Permit",
    "Description": "An art gallery that offers complimentary beer, wine and liquor for consumption only on the premises.\nThis is not a license to sell alcohol, but a permit to serve it on a complimentary basis.\nAn art gallery permittee shall not, directly or indirectly, sell alcohol beverages by the drink, shall not serve alcohol beverages for more than four hours in any one day, and shall not serve alcohol beverages more than fifteen days per year of licensure.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Arts Liquor License",
    "Record Type": "Alcohol/Specialty/Arts Liquor/License",
    "Description": "Issued to non-profit arts organizations and municipally owned arts facilities (e.g. Art Museum, Museum of Nature and Science) that offer performances or productions of an artistic or cultural nature.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Arts Liquor Application",
    "Record Type": "Alcohol/Specialty/Arts Liquor/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Arts Liquor Renewal",
    "Record Type": "Alcohol/Specialty/Arts Liquor/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "On-Site Sale and Consumption Liquor Permit",
    "Record Type": "Alcohol/Specialty/On-Site Sale and Consumption/Permit",
    "Description": "ABRA: Manufacturer's On-Site Sales and Consumption Permit: Allows a spirit, beer or wine manufacturer to sell the products it manufactures for consumption on the licensed premises",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Race Track Liquor License",
    "Record Type": "Alcohol/Specialty/Race Track/License",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Race Track Liquor Application",
    "Record Type": "Alcohol/Specialty/Race Track/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Race Track Liquor Renewal",
    "Record Type": "Alcohol/Specialty/Race Track/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Special Event Liquor Permit",
    "Record Type": "Alcohol/Specialty/Special Event/Permit",
    "Description": "Special event liquor permits the sale by the drink only of Malt, Vinous and Spirituous liquor,  or fermented malt beverages (3.2 Beer) , on premises that do not hold a liquor license or is to be sold by a qualifying organization or club or arts liquor licensed premises.\nQualifying organizations include:\nNon profit organizations\nSocial, fraternal, patriotic, political or athletic in nature (not organized for a monetary gain)\nState Agencies\nAn instrumentality of a municipality or country\nPolitical candidate who has filed necessary reports and statements with the  State.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Vintner's Restaurant Liquor License",
    "Record Type": "Alcohol/Specialty/Vintner's Restaurant/License",
    "Description": "Vintner's restaurant is a retail establishment that sells food for consumption on the premises and that manufactures no more than 250,000 gallons of wine on its premises each year.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Vintner's Restaurant Liquor Application",
    "Record Type": "Alcohol/Specialty/Vintner's Restaurant/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Vintner's Restaurant Liquor Renewal",
    "Record Type": "Alcohol/Specialty/Vintner's Restaurant/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Farm Winery License",
    "Record Type": "Alcohol/Supplier/Farm Winery/License",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Farm Winery Application",
    "Record Type": "Alcohol/Supplier/Farm Winery/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Farm Winery Renewal",
    "Record Type": "Alcohol/Supplier/Farm Winery/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Liquor Manufacturer License",
    "Record Type": "Alcohol/Supplier/Manufacturer/License",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Liquor Manufacturer Application",
    "Record Type": "Alcohol/Supplier/Manufacturer/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Liquor Manufacturer Renewal",
    "Record Type": "Alcohol/Supplier/Manufacturer/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Winery License",
    "Record Type": "Alcohol/Supplier/Winery/License",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Winery Application",
    "Record Type": "Alcohol/Supplier/Winery/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Winery Renewal",
    "Record Type": "Alcohol/Supplier/Winery/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Temporary Liquor Establishment Permit",
    "Record Type": "Alcohol/Temporary/Establishment/Permit",
    "Description": "Temporary License: Temporarily permits the sale and service of alcoholic beverages for up to four days at banquets, picnics, bazaars, fairs or similar public gatherings.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Self-Distribution Liquor Wholesaler License",
    "Record Type": "Alcohol/Wholesaler/Self-Distribution/License",
    "Description": "Wholesaler: Sells alcoholic beverages to other District ABC licensees for resale.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Self-Distribution Liquor Wholesaler Application",
    "Record Type": "Alcohol/Wholesaler/Self-Distribution/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Self-Distribution Liquor Wholesaler Renewal",
    "Record Type": "Alcohol/Wholesaler/Self-Distribution/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Liquor Wholesale Warehousing License",
    "Record Type": "Alcohol/Wholesaler/Warehousing/License",
    "Description": "UT_ license for the purpose of warehousing, distribution, and transportation of liquor.",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Liquor Wholesale Warehousing Application",
    "Record Type": "Alcohol/Wholesaler/Warehousing/Application",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "Liquor Wholesale Warehousing Renewal",
    "Record Type": "Alcohol/Wholesaler/Warehousing/Renewal",
    "Description": "Refer to License Record",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "Configuration",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  },
  {
    "Name": "",
    "Record Type": "",
    "Description": "",
    "Purchase Status": "",
    "Package Status": "",
    "Status": "",
    "Record ID Mask": "",
    "Workflow": "",
    "Status Group": "",
    "Custom Field Group": "",
    "Custom List": "",
    "Intake Form": "",
    "Pageflow": "",
    "Fee Schedule": "",
    "Inspection Group": "",
    "Document Group": "",
    "Expiration Code": ""
  }
]